### ISSUE TITLE
1.15 version tips

### ISSUE THREAD

**Issue by ghost** [ixkaito/one-dark-monokai#2]
![default](https://cloud.githubusercontent.com/assets/10335245/24028380/5ed0601e-0b09-11e7-81bf-5fb95a2449c2.PNG)

**Comment by ixkaito** [comment]
@hilexpierce Thanks!

`:host` is for backward compatibility for a while. I'll remove it in the next version.

**Comment by ixkaito** [comment]
Fixed in [v0.5.0](https://github.com/ixkaito/one-dark-monokai/releases/tag/v0.5.0).
